[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# NOTE: For production, proxy API calls to your deployed backend.
# Replace YOUR_BACKEND_URL below (e.g. https://api.yourdomain.com)
# [[redirects]]
#   from = "/api/*"
#   to = "https://YOUR_BACKEND_URL/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

