[phases.setup]
nixPkgs = ['python311', 'nodejs_18', 'npm']

[phases.build]
cmds = [
    'cd frontend && npm install && npm run build',
    'pip install -r requirements.txt'
]

[phases.start]
cmd = 'python backend/main.py'

[variables]
NODE_VERSION = '18'
PYTHON_VERSION = '3.11'
